# Generated by Django 3.1.7 on 2021-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topper_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_rank', models.IntegerField()),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_percentage', models.FloatField()),
                ('stu_year', models.IntegerField()),
                ('session', models.CharField(max_length=9)),
            ],
        ),
    ]
