# Generated by Django 3.1.7 on 2021-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_placement_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_list',
            name='file',
            field=models.FileField(upload_to='project_file/'),
        ),
    ]
