# Generated by Django 3.1.7 on 2021-06-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_name', models.CharField(max_length=100)),
                ('recruiter_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
