# Generated by Django 3.1.7 on 2021-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter_pic',
            field=models.ImageField(upload_to='recruiters/'),
        ),
    ]
