# Generated by Django 3.1.7 on 2021-06-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50)),
                ('product_pic', models.ImageField(upload_to='product_image/')),
                ('product_description', models.CharField(max_length=500)),
            ],
        ),
    ]
