# Generated by Django 3.1.7 on 2021-06-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teaching_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('profile_pic', models.ImageField(max_length=70, upload_to='teaching_staff/')),
                ('designation', models.CharField(max_length=70)),
                ('qualification', models.CharField(max_length=70)),
                ('area_of_interest', models.CharField(max_length=70)),
            ],
        ),
    ]
