# Generated by Django 3.1.7 on 2021-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper_title', models.CharField(max_length=200)),
                ('question_paper_file', models.FileField(max_length=200, upload_to='question_paper/')),
            ],
        ),
        migrations.CreateModel(
            name='usefull_format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_title', models.CharField(max_length=200)),
                ('format_file', models.FileField(max_length=200, upload_to='usefull_format/')),
            ],
        ),
        migrations.CreateModel(
            name='usefull_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=200)),
                ('link_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(max_length=200),
        ),
    ]
